# Generated by Django 3.2 on 2021-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('house', 'House'), ('jobe', 'Jobe'), ('food', 'Food'), ('games', 'Games'), ('sundry', 'Sundry')], default='sundry', max_length=200),
        ),
    ]
