# Generated by Django 3.2 on 2021-05-01 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appraisal',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='moder_check',
            field=models.BooleanField(default=False),
        ),
    ]
