# Generated by Django 3.2 on 2021-05-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210501_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': [('user_add_or_del', 'Удаление или добавление bool')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
